name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build and export the Next.js app
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "your@email.com"
          git config --global user.name "Your Name"
          git checkout --orphan gh-pages
          git --work-tree out/ add --all
          git --work-tree out/ commit -m "GitHub Pages Deployment"
          git push origin HEAD:gh-pages --force
        env:
          echo "NEXT_PUBLIC_OPENAI_KEY=${{ secrets.NEXT_PUBLIC_OPENAI_KEY }}" >> .env.local
          echo "NEXT_PUBLIC_RESEND_ACCESS_TOKEN=re_LGQe23Vp_MuhqpgXAwus6qs33txP3pEDg" >> .env.local
          echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}" >> .env.local
          echo "NEXT_PUBLIC_STRIPE_SECRET_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_SECRET_KEY }}" >> .env.local
        if: success()

